config/routes.rb
AuthInRails::Application.routes.draw do

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  get "close_task" => "tasks#close", :as => "close_task"
  get "reopen_task" => "tasks#reopen", :as => "reopen_task"
  get "delete_tasks" => "tasks#destroy", :as => "delete_tasks"
  get "transfer_hotel/:id" => "hotels#transfer", :as => "transfer_hotel"
  put "do_transfer" => "hotels#do_transfer", :as => "do_transfer"
  resources :users
  resources :sessions
  resources :hotels
  resources :tasks
  resources :contacts
  resources :notes
  root :to => "users#new"

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	has_and_belongs_to_many :hotels
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
	attr_accessible :phone, :inncode, :name, :address, :city, :state, :global_web_url, :local_web_url, :facebook_url, :twitter_url
	validates_uniqueness_of :inncode
	validates_presence_of :inncode, :name
	has_and_belongs_to_many :users
	has_and_belongs_to_many :tasks
	has_and_belongs_to_many :contacts
	has_many :notes
	accepts_nested_attributes_for :notes
end

app/models/note.rb
class Note < ActiveRecord::Base
	attr_accessible :note_detail, :string, :hotel_id
	belongs_to :hotel
end

app/models/task.rb
class Task < ActiveRecord::Base
	attr_accessible :name
	has_and_belongs_to_many :hotels
	validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :email, :password, :password_confirmation
	has_secure_password
	validates_presence_of :password, :on=>:create
	has_and_belongs_to_many :hotels
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  #force_ssl

  private 
  def logged_in?
    unless session[:user_id]
      flash[:notice] = "You must be logged in" 
      redirect_to :controller=>"sessions", :action=>"new"
      return false
    else
      return true
    end
  end
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_filter :logged_in? 
	def new
		@contact = Contact.new
		@hotel = Hotel.find(params[:hotel_id])
	end

	def create
		@hotel = Hotel.find(params["contact"]["id"])
		@contact = Contact.new("first_name" => params[:contact][:first_name], "last_name" => params[:contact][:last_name], "phone" => params[:contact][:phone], "email" => params[:contact][:email], "title" => params[:contact][:title])
		@hotel.contacts << @contact
		if @contact.save
			redirect_to hotels_path + "/#{@hotel.id}", :notice => "Contact added"
		else
			render "new"
		end
	end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to @contact.hotels.first, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
	before_filter :logged_in? 
	def new
		@hotel = Hotel.new
	end
	def edit
    	@hotel = Hotel.find(params[:id])
	end
	def update
    	@hotel = Hotel.find(params[:id])

    	respond_to do |format|
     	if @hotel.update_attributes(params[:hotel])
       	 	format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
       	 	format.json { head :no_content }
    	 else
      	  	format.html { render action: "edit" }
       	 	format.json { render json: @hotel.errors, status: :unprocessable_entity }
    	 end
    end

	end
	def show

		@user = User.find(session[:user_id])
		if Hotel.where("id = ?", params[:id]).count  == 1 && @user.hotels.where("id = ?", params[:id]) != '[]'
			@hotel = Hotel.find(params[:id])
			@tasks = @hotel.tasks.where("status = 'open'")
			@notes = @hotel.notes
			@closed_tasks = @hotel.tasks.where("status = 'closed'")
			@contacts = @hotel.contacts
			@contact_email_list = []
			@contacts.each do |contact|
				@contact_email_list << contact.email	
			end
			@contact_email_list = @contact_email_list.join(';')
		else
			redirect_to :controller => "hotels", :action => "index"
		end
	end

	def create
		@user = User.find(session[:user_id])
		@hotel = Hotel.new(params[:hotel])
		@user.hotels << @hotel
		if @hotel.save
			redirect_to hotels_path, :notice => "Hotel added"
		else
			render "new"
		end
	end

	def index
		@user = User.find(session[:user_id])
		@hotels = @user.hotels.order("inncode")
		#@tasks = @hotels.tasks
	end

	def transfer
		@user = User.find(session[:user_id])
	  if Hotel.where("id = ?", params[:id]).count  == 1 && @user.hotels.where("id = ?", params[:id]) != '[]'
		@hotel = Hotel.find(params[:id])
	  else
	  	redirect_to :controller => "hotels", :action => "index"

	  end
	end

	def do_transfer

		@old_user_id = User.find(params[:hotel][:old_user_id])
		@hotel = Hotel.find(params[:hotel][:id])
		@new_user = User.find(params[:hotel][:user_ids])
		@hotel.users.delete(@old_user_id)
		@hotel.users << @new_user
		redirect_to hotels_path, :notice => "Hotel Transferred"


	end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
before_filter :logged_in? 
	def new
		@user = User.find(session[:user_id])
		if Hotel.where("id = ?", params[:hotel_id]).count  == 1 && @user.hotels.where("id = ?", params[:hotel_id]) != '[]' #make sure hotel exists and hotel belongs to the user
			@note = Note.new
			@hotel = Hotel.find(params[:hotel_id])
		else
			redirect_to :controller => "hotels", :action => "index"
		end
	end

	def create
		@hotel = Hotel.find(params["note"]["hotel_id"])
		@note = Note.new("note_detail" => params[:note][:note_detail], "hotel_id" => params[:note][:hotel_id])
		#@hotel.notes << @note
		respond_to do |format|
		  if @note.save
			  format.html { redirect_to @hotel }
			  format.js
		  else
			  render "new"
		  end
		 end
	end
  def destroy
    @note = Note.find(params["id"])
    @note.destroy

    respond_to do |format|
      format.html { redirect_to request.referrer }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new

	end

	def create
		user = User.find_by_email(params[:email].downcase)
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to hotels_path, :notice => "Logged in!"
		else
			flash.now.alert = "Invalid email or password"
			render "new"
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to hotels_path, :notice => "Logged out!"
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
before_filter :logged_in? 
	def new
		@user = User.find(session[:user_id])
		if Hotel.where("id = ?", params[:hotel_id]).count  == 1 && @user.hotels.where("id = ?", params[:hotel_id]) != '[]' #make sure hotel exists and hotel belongs to the user
			@task = Task.new
			@hotel = Hotel.find(params[:hotel_id])
		else
			redirect_to :controller => "hotels", :action => "index"
		end
	end

	def create
		@hotel = Hotel.find(params["task"]["id"])
		@task = Task.create!("name" => params[:task][:name])
		@hotel.tasks << @task
		respond_to do |format|
		  if @task.save
			  format.html { redirect_to hotels_path(@hotel) }
			  format.js
		  else
			  render "new"
		  end
		 end
	end

	def close
		@task = Task.find(params["task_id"])
		@task.status = 'closed'
		@task.save
		redirect_to request.referrer
	end

	def reopen
		@task = Task.find(params["task_id"])
		@task.status = 'open'
		@task.save
		redirect_to request.referrer
	end

  def destroy
    @task = Task.find(params["task_id"])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to request.referrer }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(params[:user])
		if @user.save
			session[:user_id] = @user.id
			redirect_to hotels_path, :notice => "Signed up! You are now logged in.  Add some hotels!"
		else
			render "new"
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/edit.html.erb
<h3>Editing <%= @contact.first_name + @contact.last_name%></h3>

<%= form_for @contact do |f| %>
	<% if @contact.errors.any? %>
	<div class="error messages">
	<h2>Form is invalid</h2>
	<ul>
		<% for message in @contact.errors.full_messages %>
		<li><%= message %></li>
		<% end %>
	</ul>
	</div>
	<% end %>

<div class="field">
	<%= f.label :first_name %>
	<%= f.text_field :first_name %>
</div>
<div class="field">
	<%= f.label :last_name %>
	<%= f.text_field :last_name %>
</div>
<div class="field">
	<%= f.label :title %>
	<%= f.text_field :title %>
</div>
<div class="field">
	<%= f.label :email %>
	<%= f.text_field :email %>
</div>
<div class="field">
	<%= f.label :phone %>
	<%= f.text_field :phone %>
</div>


<div class="actions"><%= f.submit %></div>
<% end %>

app/views/contacts/new.html.erb
<h3>Creating new contact for <%= @hotel.name %></h3>

<%= form_for @contact do |f| %>
	<% if @contact.errors.any? %>
	<div class="error messages">
	<h2>Form is invalid</h2>
	<ul>
		<% for message in @contact.errors.full_messages %>
		<li><%= message %></li>
		<% end %>
	</ul>
	</div>
	<% end %>

<div class="field">
	<%= f.label :first_name %>
	<%= f.text_field :first_name %>
</div>
<div class="field">
	<%= f.label :last_name %>
	<%= f.text_field :last_name %>
</div>
<div class="field">
	<%= f.label :title %>
	<%= f.text_field :title %>
</div>
<div class="field">
	<%= f.label :email %>
	<%= f.text_field :email %>
</div>
<div class="field">
	<%= f.label :phone %>
	<%= f.text_field :phone %>
</div>
  <div class="field">
    
    <%= f.hidden_field :id, :value => @hotel.id %>
  </div>


<div class="actions"><%= f.submit %></div>
<% end %>

app/views/hotels/create_task.html.erb
<h1>Add Task</h1>

<%= form_for @task do |f| %>
	<% if @task.errors.any? %>
	<div class="error messages">
	<h2>Form is invalid</h2>
	<ul>
		<% for message in @task.errors.full_messages %>
		<li><%= message %></li>
		<% end %>
	</ul>
	</div>
	<% end %>

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name %>
</div>


<div class="actions"><%= f.submit %></div>
<% end %>

app/views/hotels/edit.html.erb
<h1>Edit Hotel</h1>

<%= form_for @hotel do |f| %>
	<% if @hotel.errors.any? %>
	<div class="error messages">
	<h2>Form is invalid</h2>
	<ul>
		<% for message in @hotel.errors.full_messages %>
		<li><%= message %></li>
		<% end %>
	</ul>
	</div>
	<% end %>

<div class="field">
	<%= f.label :inncode %>
	<%= f.text_field :inncode %>
</div>

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name %>
</div>
<div class="field">
	<%= f.label :phone %>
	<%= f.text_field :phone %>
</div>
<div class="field">
	<%= f.label :address %>
	<%= f.text_field :address %>
</div>
<div class="field">
	<%= f.label :city %>
	<%= f.text_field :city %>
</div>
<div class="field">
	<%= f.label :state %>
	<%= f.text_field :state %>
</div>
<div class="field">
	<%= f.label :global_web_url %>
	<%= f.text_field :global_web_url %>
</div>
<div class="field">
	<%= f.label :local_web_url %>
	<%= f.text_field :local_web_url %>
</div>
<div class="field">
	<%= f.label :facebook_url %>
	<%= f.text_field :facebook_url %>
</div>
<div class="field">
	<%= f.label :twitter_url %>
	<%= f.text_field :twitter_url %>
</div>
<div class="actions"><%= f.submit %></div>
<% end %>

app/views/hotels/index.html.erb
<h2>My Hotels</h2>

<ul>
<% @hotels.each do |hotel| %>
  <li><%= link_to hotel.inncode + " - " + hotel.name, hotel %>
 	<% if hotel.tasks.where("status = 'open'").count > 0 %>
  	 - <small><%= hotel.tasks.where("status = 'open'").count %> open tasks</small></li>
  	<% end %>
<% end %>
</ul>

<%= link_to "Add New Hotel", new_hotel_path %>

<h3>All Open Tasks</h3>
<ul>
<% @hotels.each do |hotel| %>
	<% hotel.tasks.each do |task| %>
		<% if task.status == 'open' %>
		<li><%= link_to task.name, hotels_path + "/" + hotel.id.to_s %> (<%= hotel.inncode %>)</li>
		<% end %>
	<% end %>
<% end %>
</ul>

app/views/hotels/new.html.erb
<h1>Add Hotel</h1>

<%= form_for @hotel do |f| %>
	<% if @hotel.errors.any? %>
	<div class="error messages">
	<h2>Form is invalid</h2>
	<ul>
		<% for message in @hotel.errors.full_messages %>
		<li><%= message %></li>
		<% end %>
	</ul>
	</div>
	<% end %>

<div class="field">
	<%= f.label :inncode %>
	<%= f.text_field :inncode %>
</div>

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name %>
</div>
<div class="field">
	<%= f.label :phone %>
	<%= f.text_field :phone %>
</div>
<div class="field">
	<%= f.label :address %>
	<%= f.text_field :address %>
</div>
<div class="field">
	<%= f.label :city %>
	<%= f.text_field :city %>
</div>
<div class="field">
	<%= f.label :state %>
	<%= f.text_field :state %>
</div>
<div class="field">
	<%= f.label :global_web_url %>
	<%= f.text_field :global_web_url %>
</div>
<div class="field">
	<%= f.label :local_web_url %>
	<%= f.text_field :local_web_url %>
</div>
<div class="field">
	<%= f.label :facebook_url %>
	<%= f.text_field :facebook_url %>
</div>
<div class="field">
	<%= f.label :twitter_url %>
	<%= f.text_field :twitter_url %>
</div>

<div class="actions"><%= f.submit %></div>
<% end %>

app/views/hotels/show.html.erb

<div style="padding:25px">
<h3 style="display:inline"><%= link_to "Hotels", hotels_path %> > <%= @hotel.name %></h3> &nbsp;&nbsp;   <small><%= link_to "Edit", edit_hotel_path %></small>
</div>
<div class="row">
        <div class="col-md-4">
          <h2>Summary</h2>

          <p><strong>Phone</strong>: <%= @hotel.phone %><br /><br />
          <strong>Address</strong><br>
				<%= @hotel.address %><br />
             <%= @hotel.city %>, <%= @hotel.state  %><br><br>
             <strong>Links</strong><br>
             <%= link_to "Global Web <br>".html_safe, @hotel.global_web_url, target: "_blank" %>
             <%= link_to "Local Site <br>".html_safe, @hotel.local_web_url, target: "_blank" unless @hotel.local_web_url == ""  %>
             <%= link_to "FaceBook <br>".html_safe, @hotel.facebook_url, target: "_blank" unless @hotel.facebook_url == "" %>
             <%= link_to "Twitter <br>".html_safe, @hotel.twitter_url, target: "_blank" unless @hotel.twitter_url == "" %>

            </p>
        </div>
        <div class="col-md-8">
          <h2>Contacts</h2>
          <% if @contacts.empty? %>
			<em>No contacts saved for this hotel</em>
		  <% else %>
		<table class="table table-hover">
		<thead>
			<tr>
			  <th>Name</th>
	 		 <th>Title</th>
	 		 <th>Email</th>
	 		 <th></th>
			</tr>
		</thead>
		<tbody>
			<% @contacts.each do |contact| %>

			<tr>
			  <td><%= contact.first_name + " " + contact.last_name %></td>
	 		 <td><%= contact.title %></td>
	 		 <td><%= link_to contact.email, "mailto:" + contact.email %></td>
	 		  <td><%= link_to "Edit", edit_contact_path(contact) %></td>
			</tr>

			<% end %>
			</tbody>
		</table>

			<%= link_to "Email Group", "mailto:" + @contact_email_list, :class=>'btn btn-xs btn-primary' %> 
		<% end %>
		<%= link_to "Add Contact", new_contact_path + "?hotel_id=" + @hotel.id.to_s, :class=>'btn btn-xs btn-primary' %>

       </div>

      </div>
<div class='row'><div class='span12'><hr /></div></div>

	<div class="row">
        <div class="col-md-5">
          <h3>Currently Open Tasks</h3>

			<% if @tasks.empty? %>
			<div id="tasks">
			</div>
			<% else %>
			<div id="tasks">
				<%= render :partial => @tasks, :locals => { :list => true } %>


			</div>
			<% end %>
			<br>
			<%= form_for(Task.new, :remote => true) do |f| %>
 			<%= f.hidden_field :id, :value => @hotel.id %>
			<table>
				<tr>
				  <td>
				<%= f.text_field :name %></td>
				<td><%= f.submit %></td></tr>
			</table>
			<% end %>

        </div>
        <div class="col-md-7">
<h3>Closed Tasks</h3>
<ul>
<% if @closed_tasks.empty? %>
<li><em>No closed tasks for this hotel</em></li>
<% else %>
<% @closed_tasks.each do |task| %>
<li><%= task.name %> - <em>Closed on <%= task.updated_at.strftime("%b %-d %Y") %></em> - <%= link_to "Reopen Task", reopen_task_path + "?task_id=" + task.id.to_s %> - <%= link_to "Delete Task", delete_tasks_path + "?task_id=#{task.id.to_s}" %></li>
<% end %>
<% end %>
</ul>

       </div>

      </div>



<div class='row'><div class='span12'><hr /></div></div>

<h3>Hotel Notes</h3>

<% if @notes.empty? %>
<div id="notes" class="container">

</div>
<% else %>
<div id="notes" class="container">
	<%= render :partial => @notes, :locals => { :list => true } %>
</div>
<% end %>
<br>
<%= form_for(Note.new, :remote => true) do |f| %>
 <%= f.hidden_field :hotel_id, :value => @hotel.id %>
<table>
	<tr>
	  <td>
	<%= f.text_area :note_detail, :cols => "100", :rows => "5" %></td>
	</tr>
	<tr>
	<td><%= f.submit %></td></tr>
</table>
<% end %>

<br><br>
<small><%= link_to "Transfer Ownership", transfer_hotel_path(@hotel.id) %></small>

app/views/hotels/transfer.html.erb
<h3>Transfer Hotel Ownership for <%= @hotel.name %></h3>



<p>Current Manager: <%= @hotel.users.first.email %></p>

<p>Transfer To</p>

<%= form_for @hotel, :url => { :action => "do_transfer" } do |f| %>
	<% if @hotel.errors.any? %>
	<div class="error messages">
	<h2>Form is invalid</h2>
	<ul>
		<% for message in @hotel.errors.full_messages %>
		<li><%= message %></li>
		<% end %>
	</ul>
	</div>
	<% end %>

	  <div class="field">
    
    <%= f.hidden_field :id, :value => @hotel.id %>
  </div>
	  <div class="field">
    
    <%= f.hidden_field :old_user_id, :value => @hotel.users.first.id %>
  </div>
<div class="field">
<%= f.collection_select(:user_ids, User.all, :id, :email) %>
</div>
<br>
<div class="actions"><%= f.submit :confirm=>"Are you sure you wish to transfer ownership?" %></div>


<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>eCommerce Portfolio Manager</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag  "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" %>
  <%= javascript_include_tag  "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js" %>
  <%= javascript_include_tag "http://shmopper2.googlecode.com/svn/trunk/public/javascripts/jquery-rails.js" %>

  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller] %>">
  <div id="container">
<!--________________________________________________ -->

 <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Portfolio Manager", hotels_path, :class=> "navbar-brand" %>

        </div>
        <div class="navbar-collapse collapse">
          <form class="navbar-form navbar-right" role="form">
          <% if current_user %>
           <p class="navbar-text pull-right">Logged in as <%= current_user.email %> -   
           <%= link_to "Log out", logout_path %></p>
          <% else %>
           <p class="navbar-text pull-right"><%= link_to "Sign up", signup_path %> or
           <%= link_to "log in", login_path %></p>
          <% end %>
           <!-- <button type="submit" class="btn btn-success">Sign in</button> -->
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </div>

    <!-- Main jumbotron for a primary marketing message or call to action -->


    <div class="container">
        <% flash.each do |name, msg| %>
     <button type="button" class="btn btn-xs btn-warning"> <%= content_tag :div, msg, :id => "flash_#{name}" %></button>
    <% end %>
    <div style="padding:25px"></div>
    <%= yield %>
      <div class="row">
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; Company 2014</p>
      </footer>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
  </body>



<!--___________________________________________________-->



</html>

app/views/notes/_note.html.erb
<%= div_for note do %>

<%= note.note_detail %> - <%= link_to 'Delete Note', note, confirm: 'Are you sure?', method: :delete %>
<% end %>

app/views/notes/create.js.erb
$("#notes").append("<%= escape_javascript(render(@note)) %>");
$("#new_note")[0].reset();

app/views/tasks/_task.html.erb
<%= div_for task do %>

<strong><%= task.name %></strong> - <em>Opened on <%= task.created_at.strftime("%b %-d %Y") %></em> - <%= link_to "Close Task", close_task_path + "?task_id=" + task.id.to_s %>

<% end %>

app/views/tasks/create.js.erb
$("#tasks").append("<%= escape_javascript(render(@task)) %>");
$("#new_task")[0].reset();

app/views/tasks/new.html.erb
<h3>Creating new task for <%= @hotel.name %></h3>

<%= form_for @task do |f| %>
	<% if @task.errors.any? %>
	<div class="error messages">
	<h2>Form is invalid</h2>
	<ul>
		<% for message in @task.errors.full_messages %>
		<li><%= message %></li>
		<% end %>
	</ul>
	</div>
	<% end %>

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name %>
</div>
  <div class="field">
    
    <%= f.hidden_field :id, :value => @hotel.id %>
  </div>


<div class="actions"><%= f.submit %></div>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
	<div class="error messages">
	<h2>Form is invalid</h2>
	<ul>
		<% for message in @user.errors.full_messages %>
		<li><%= message %></li>
		<% end %>
	</ul>
	</div>
	<% end %>

<div class="field">
	<%= f.label :email %>
	<%= f.text_field :email %>
</div>

<div class="field">
	<%= f.label :password %>
	<%= f.password_field :password %>
</div>

<div class="field">
	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %>
</div>

<div class="actions"><%= f.submit %></div>
<% end %>